# Copyright Erik Lönroth, <erik.lonroth@gmail.com>
# License: Apache2
#
#
# See: https://docs.gitlab.com/runner/configuration/advanced-configuration.html

options:
  gitlab-authentication-token:
    type: string
    default: ""
    description: | 
      "MANDATORY: Runner authentication token. Get it from you gitlab instance, group or project starting.
      Runner authentication tokens have the prefix 'glrt-' for the token"

  gitlab-server:
    type: string
    default: ""
    description: "MANDATORY: gitlab server to use. E.g. https://gitlab.example.com"

  gitlab-runner-architecture:
    type: string
    default: "amd64"
    description: |
      "Architecture of the gitlab runner debian package to download"

  docker-image:
    type: string
    default: "docker:latest"
    description: |
      "Deployment only config. The docker image to use for docker runners."

  docker-in-docker:
    type: boolean
    default: false
    description: |
      "Allow for running Docker in Docker using socks"

  executor:
    type: string
    default: "docker"
    description: |
      "MANDATORY: Can be: docker or lxd. Determines if this runner 
       uses a lxd or docker executor. E.g. select [docker | lxd]"

  docker_pull_policy:
    type: string
    default: "always"
    description: |
      "For docker executors the pull behavior can be modified. Defaults to always pull image regardless if available or not.
      Available options: "always", "never", "if-not-present"

  https_proxy:
    type: string
    default: ""
    description: "A https proxy url E.g. https://proxy.example.com:8080/"

  http_proxy:
    type: string
    default: ""
    description: "A http proxy url E.g. http://proxy.example.com:8080/"

  docker-tmpfs:
    type: string
    default: ""
    description:  |
      "Docker executor temporary file system configuration for tmpfs.
       Path and config separated by a ':'. E.g. /scratch:rw,exec,size=1g"